-- Kanto climbing gym baseline.
-- Source: Rockgym prefecture directory pages, verified on 2026-05-10.
-- This seed intentionally stores directory-confirmed existence first. Official
-- site details should progressively replace each row's source fields as they
-- are verified.

INSERT INTO "gyms" (
  "source_external_id",
  "name",
  "description",
  "area",
  "source_type",
  "source_url",
  "source_attribution",
  "source_verified_at",
  "source_policy",
  "status"
)
VALUES
  ('rockgym:tokyo:prime-climbing', 'PRIME（プライム） クライミング', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '中央区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:boulcom-tokyo', 'BOULCOM（ボルコム） 東京店', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '千代田区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:sorayon', 'ボルダリングジム 空の向こうへ四足歩行（そらよん）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '港区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:spider', 'クライミングジム SPIDER（スパイダー）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '港区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:urban-base-camp-shinjuku', 'Urban Base Camp（アーバンベースキャンプ） 新宿', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '新宿区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:everfree', 'EVERFREE（エバーフリー） クライミングジム', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '新宿区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:rocky-shinjuku-akebonobashi', 'ROCKY（ロッキー） 新宿曙橋店', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '新宿区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:beta', 'BETA（ベータ） クライミングジム', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '新宿区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:parkers-tokyo', 'PARKERS TOKYO', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '新宿区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:noborock-takadanobaba', 'NOBOROCK（ノボロック）高田馬場', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '新宿区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:noborock-ikebukuro', 'NOBOROCK（ノボロック） 池袋店', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '豊島区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:js-ikebukuro', 'スポーツクライミングスクール・ジム J&S 池袋', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '豊島区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:konami-ikebukuro', 'コナミスポーツクラブ 池袋', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '豊島区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:spodori', 'スポドリ！', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '文京区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:base-camp-tokyo-edogawabashi', 'Base Camp Tokyo（ベースキャンプ東京）江戸川橋店', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '文京区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:boulders', 'BOULDERS（ボルダーズ） クライミングジム', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '足立区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:galaxcity', 'ギャラクシティ', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '足立区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:rhino-and-bird', 'Rhino and Bird（ライノアンドバード）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '荒川区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:hutte', 'クライミングジム Hutte（ヒュッテ）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '荒川区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:deer', 'ボルダリング deer（ディア）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '江戸川区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:rocklands', 'クライミングジム ROCKLANDS（ロックランズ）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '江戸川区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:bears-rock', 'ボルダリングジム BEAR’S ROCK（ベアーズロック）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '葛飾区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:katsushika-sports-climbing-center', '葛飾区東金町運動場 スポーツクライミングセンター', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '葛飾区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:fish-and-bird', 'Fish and Bird（フィッシュアンドバード）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '江東区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:fukagawa-sports-center', '深川スポーツセンター', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '江東区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:base-camp-tokyo-kinshicho', 'Base Camp Tokyo（ベースキャンプ東京）錦糸町店', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '江東区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:livedoor-urban-sports-park', 'livedoor URBAN SPORTS PARK（ライブドアアーバンスポーツパーク）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '江東区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:headrock', 'HEADROCK（ヘッドロック） クライミングジム', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '墨田区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:nico', 'クライミングジム NICO（ニコ）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '墨田区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:the-stone-session-tokyo', 'THE STONE SESSION TOKYO', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '墨田区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:granny-higashiueno', 'ボルダリングジム グラニー 東上野店', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '台東区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:b-pump-ogikubo', 'B-PUMP OGIKUBO 荻窪', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '杉並区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:bleau', 'ボルダリングスペース BLEAU（ブロー）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '杉並区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:lago', 'フィットネスクライミングスタジオ LAGO（ラーゴ）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '杉並区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:cell', 'クライミングジム CELL（セル）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '世田谷区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:exciting-sancha', 'スポーツクライミングジム エキサイティング三茶', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '世田谷区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:quail', 'Quail（クエール） クライミングジム', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '練馬区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:pop-in', 'ボルダリングジム POP IN（ポップイン）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '大田区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:piglet', 'PIGLET（ピグレット） クライミングジム', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '品川区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:north-park', 'ノースパークビル ボルダリングジム', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '板橋区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:the-factory', 'the FACTORY（ファクトリー）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '板橋区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:dracaena', 'クライミングジム ドラセナ', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '板橋区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:underground', 'ボルダリングジム UNDERGROUND（アンダーグラウンド）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '北区', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:camelopardalis', 'クライミングスタジオ カメロパルダリス', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '昭島市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:play', 'クライミングジム＆ヨガスタジオ PLAY', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '昭島市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:runout', 'クライミングジム ランナウト', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '国分寺市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:jet-set', 'JET SET（ジェットセット） climbing gym', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '立川市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:d-bouldering-plus-lead-tachikawa', 'ディーボルダリングプラスリード立川', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '立川市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:westrock-chofu', 'クライミングジム WESTROCK（ウエストロック） 調布店', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '調布市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:hangout', 'クライミングジム hangout（ハングアウト）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '調布市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:giri-giri', 'クライミングジム GIRI.GIRI（ギリギリ）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '西東京市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:westrock-fuchu', 'クライミングジム WESTROCK（ウエストロック） 府中店', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '府中市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:jam-session-mitaka', 'ボルダリングジム ジャムセッション三鷹', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '三鷹市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:isara', 'クライミングカフェ isara（イサラ）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '三鷹市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:volny', 'クライミングジム VOLNY（ボルニー）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '武蔵野市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:mitaka-gym', 'ロッククライミング 三鷹ジム', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '武蔵野市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:maboo', 'クライミングジム MABOO（マーブー）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '武蔵村山市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:maghreb-est', 'マグレブエスト', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '多摩市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:d-bouldering-hachioji', 'ディーボルダリング 八王子', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '八王子市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:madrock', 'クライミングジム マッドロック', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '八王子市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:rockbeans', 'クライミングジム ROCKBEANS（ロックビーンズ）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '八王子市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:d-bouldering-plus-nishi-hachioji', 'ディーボルダリングプラス 西八王子', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '八王子市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:noborock-machida', 'NOBOROCK（ノボロック） 町田店', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '町田市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:nose-machida', 'クライミングジム NOSE（ノーズ） 町田店', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '町田市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:fits', 'Fits（フィッツ） クライミングジム', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '町田市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:caramba', 'CLIMBING FRONT CARAMBA（カランバ）', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '西多摩郡', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tokyo:miyake-recreation-center', '三宅村レクリエーションセンター', 'Rockgymの東京都クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '三宅村', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tokyo/', 'Rockgym 東京都のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),

  ('rockgym:kanagawa:sea-rock', 'クライミングジム SEA ROCK（シーロック）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '足柄下郡', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:cipher', 'クライミングジム Cipher（サイファー）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '足柄下郡', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:lamp-plus-aiko-ishida', 'ボルダリングジム Lamp+（ランププラス） 愛甲石田店', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '厚木市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:hann2-atsugi', 'ボルダリングジム 攀（HANN2） 厚木店', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '厚木市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:d-bouldering-hon-atsugi', 'ディーボルダリング本厚木', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '厚木市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:ledge', 'クライミングスペース Ledge（レッジ）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '海老名市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:wisteria', 'クライミング Wisteria（ウィステリア）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '小田原市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:pump2-kawasaki', 'PUMP2 川崎', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '川崎市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:boulcom-kawasaki', 'BOULCOM（ボルコム） 川崎店', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '川崎市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:dogwood-takatsu', 'DOGWOOD（ドッグウッド） クライミングジム 高津店', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '川崎市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:pocket', 'クライミングジム POCKET（ポケット）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '川崎市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:noborock-mizonokuchi', 'NOBOROCK（ノボロック） 溝ノ口店', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '川崎市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:boulder-boys-klub', 'ボルダリングジム Boulder Boys Klub', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '川崎市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:bolbol', 'BolBol（ボルボル）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '相模原市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:stone-magic', 'クライミングパーク STONE MAGIC（ストーンマジック）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '相模原市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:kachill', 'KaChill カチル', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '茅ヶ崎市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:kanagawa-mountain-sports-center', '神奈川県立 山岳スポーツセンター', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '秦野市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:hadano-tanzawa-climbing-park', 'はだの丹沢クライミングパーク', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '秦野市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:sloth', 'クライミングジム SLOTH（スロース）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '平塚市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:rock-and-wall', 'ボルダリングジム Rock&Wall（ロックアンドウォール）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '藤沢市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:j-wall', 'クライミングジム J-WALL', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '藤沢市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:hat', 'ボルダリングスペース HAT（ハット）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '大和市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:forge-bouldering', 'Forge bouldering', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横須賀市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:rockspot', 'ボルダリングジム ROCKSPOT（ロックスポット）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横浜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:rise', 'クライミングジム RISE（ライズ）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横浜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:grimrock', 'GRIMROCK（グリムロック） クライミングジム', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横浜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:b-pump-yokohama', 'B-PUMP YOKOHAMA 横浜', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横浜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:project', 'クライミングジム Project（プロジェクト）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横浜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:climbing-bum-yokohama', 'クライミングバム 横浜店', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横浜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:big-rock-hiyoshi', 'クライミングジム ビッグロック 日吉店', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横浜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:aladdin', 'Aladdin（アラジン） クライミング', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横浜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:share', 'ボルダリングジム Share（シェア）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横浜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:speedy', 'ボルダリングジム SPEEDY（スピーディー）', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横浜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:d-bouldering-tsunashima', 'ディーボルダリング 綱島', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横浜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:mammut-yokohama', 'MAMMUT ボルダリングジム 横浜', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横浜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:folk', 'folk（フォーク） ボルダリングジム', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横浜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:peradora-yokohama', 'PERADORA（ペルアドラ） クライミングジム 横浜', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '横浜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:kanagawa:hann1-samukawa', 'ボルダリングジム 攀（HANN1） 寒川店', 'Rockgymの神奈川県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '高座郡', 'directory_crosscheck', 'https://rockgym.jp/gym-all/kanagawa/', 'Rockgym 神奈川県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),

  ('rockgym:saitama:bonobo', 'BONOBO（ボノボ） ボルダリングスペース', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '上尾市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:limestone', 'LIMESTONE（ライムストーン） クライミングクラブ', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '入間郡', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:base-camp-iruma', 'Climb Park Base Camp（ベースキャンプ） 入間店', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '入間市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:b3-kasukabe', 'ボルダリングサイトB3春日部', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '春日部市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:kazo-gymnasium', '加須市民体育館', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '加須市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:maru', 'クライミングジム MARU（マル）', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '川口市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:pump1-kawaguchi', 'クライミングジム PUMP1 川口', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '川口市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:craze-kawaguchi', 'craze（クレイズ） ボルダリングジム 川口店', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '川口市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:rockcraft-kawagoe', 'ROCKCRAFT（ロッククラフト）川越', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '川越市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:monolithe', 'Monolithe（モノリス） ボルダリングジム', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '川越市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:konami-kawagoe', 'コナミスポーツクラブ 川越', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '川越市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:zero-saitama', 'クライミングジム ZE-RO（ゼロ） さいたま店', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '北足立郡', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:walrus', 'クライミングジム Walrus（ウォルラス）', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '久喜市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:overground', 'ボルダリングジム OVERGROUND（オーバーグラウンド）', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '鴻巣市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:be-born', 'Be born（ビーボーン） クライミングジム', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '越谷市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:rock-cube', 'ROCK CUBE（ロックキューブ） クライミングジム', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '越谷市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:penguin', 'クライミングジム Penguin（ペンギン）', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', 'さいたま市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:energy-urawa', 'エナジークライミングジム 浦和店', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', 'さいたま市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:noborock-omiya', 'NOBOROCK（ノボロック） 大宮', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', 'さいたま市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:kalma', 'KALMA（カルマ） クライミングジム', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '坂戸市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:trip', 'クライミングジム TRIP', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '坂戸市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:rout-f', 'Rout f（ルートエフ） ボルダリングジム', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '新座市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:next-gen-bouldering', 'Next Gen Bouldering（ネクストジェンボルダリング）', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '新座市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:ogano-climbing-park', '小鹿野町クライミングパーク 神怡舘', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '秩父郡', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:base-camp-hanno', 'Boulder Park Base Camp（ベースキャンプ） 飯能店', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '飯能市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:trick-star', 'TRICK STAR（トリックスター） クライミングジム', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '飯能市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:fukaya-climbing-village', '深谷クライミングヴィレッジ', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '深谷市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:lutra-lutra', 'Lutra Lutra（ルトラルトラ）', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '深谷市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:three-peaks', 'クライミングジム THREE PEAKS（スリーピークス）', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '本庄市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:okku-rock', 'クライミングハウス OKKU ROCK（オックロック）', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '南埼玉郡', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:saitama:community-park-yashio', 'Community Park Yashio', 'Rockgymの埼玉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '八潮市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/saitama/', 'Rockgym 埼玉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),

  ('rockgym:chiba:rocky-inzai', 'ROCKY（ロッキー） 印西店', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '印西市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:matsuyamashita-gymnasium', '松山下公園総合体育館', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '印西市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:energy-kashiwa', 'エナジークライミングジム 柏店', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '柏市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:altior', 'ALTIOR（アルティオール）クライミングジム', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '柏市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:funny', 'ボルダリングガレージ FUNNY（ファニー）', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '鎌ヶ谷市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:d-bouldering-plus-soga', 'ディーボルダリングプラス蘇我', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '千葉市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:tohan-dojo', 'ボルダリングジム 登攀道場', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '千葉市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:asuka', 'クライミング飛鳥', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '千葉市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:beaks', 'BEAKS（ビークス） クライミングスタジオ', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '千葉市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:d-bouldering-plus-lead-kaihimmakuhari', 'ディーボルダリングプラスリード海浜幕張', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '千葉市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:olioli', 'クライミングジム OliOli（オリオリ）', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '長生郡', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:granny-minami-nagareyama', 'ボルダリングジム GRANNY（グラニー） 南流山店', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '流山市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:sarukichi', 'クライミングジム猿吉', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '東金市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:d-bouldering-plus-tsudanuma', 'ディーボルダリングプラス津田沼', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '習志野市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:rocky-funabashi', 'ROCKY（ロッキー） 船橋店', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '船橋市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:carche-roche', 'クライミングパーク カルチェロッシュ', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '松戸市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:chiba:d-bouldering-plus-yachiyo', 'ディーボルダリングプラス八千代', 'Rockgymの千葉県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '八千代市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/chiba/', 'Rockgym 千葉県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),

  ('rockgym:ibaraki:rocky-tsukuba-ami', 'ROCKY（ロッキー） つくば阿見店', 'Rockgymの茨城県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '稲敷郡', 'directory_crosscheck', 'https://rockgym.jp/gym-all/ibaraki/', 'Rockgym 茨城県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:ibaraki:vortex', 'ボルダリングジム Vortex（ボルテックス）', 'Rockgymの茨城県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '笠間市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/ibaraki/', 'Rockgym 茨城県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:ibaraki:aoroc', 'ao_roc.（アオロク） climbing', 'Rockgymの茨城県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '鹿嶋市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/ibaraki/', 'Rockgym 茨城県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:ibaraki:style-crew', 'ボルダリングジム Style crew', 'Rockgymの茨城県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '猿島郡', 'directory_crosscheck', 'https://rockgym.jp/gym-all/ibaraki/', 'Rockgym 茨城県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:ibaraki:spole', 'Spole（スポーレ） クライミングジム', 'Rockgymの茨城県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', 'つくば市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/ibaraki/', 'Rockgym 茨城県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:ibaraki:monkey-magic-tsukuba', 'ボルダリングジム モンキーマジック つくばQ’t', 'Rockgymの茨城県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', 'つくば市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/ibaraki/', 'Rockgym 茨城県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:ibaraki:echoes', 'ECHOES CLIMBING（エコーズ クライミング）', 'Rockgymの茨城県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', 'つくばみらい市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/ibaraki/', 'Rockgym 茨城県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:ibaraki:freiheit', 'ボルダリングジム フライハイト', 'Rockgymの茨城県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '土浦市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/ibaraki/', 'Rockgym 茨城県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:ibaraki:zero-mito', 'クライミングジム ZE-RO（ゼロ） 水戸店', 'Rockgymの茨城県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '水戸市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/ibaraki/', 'Rockgym 茨城県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:ibaraki:avue', '水戸シティロックジム avue（アヴュー）', 'Rockgymの茨城県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '水戸市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/ibaraki/', 'Rockgym 茨城県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),

  ('rockgym:tochigi:mountain-cliff', 'MOUNTAIN CLIFF（マウンテンクリフ）', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '足利市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tochigi:lost-canyon', 'クライミングジム LOST CANYON（ロストキャニオン）', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '宇都宮市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tochigi:suncul', 'SUNCUL（サンカル）', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '宇都宮市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tochigi:flash', 'クライミングジム FLASH（フラッシュ）', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '宇都宮市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tochigi:zero-utsunomiya-shimoguri', 'クライミングジム ZE-RO（ゼロ） 宇都宮下栗店', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '宇都宮市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tochigi:zero-utsunomiya', 'クライミングジム ZE-RO（ゼロ） 宇都宮店', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '宇都宮市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tochigi:rockyn', 'クライミングジム RocKY’N（ロッキン）', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '宇都宮市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tochigi:ark', 'クライミングジム アーク', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '大田原市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tochigi:prost', 'Prost（プロスト） クライミングクラブ', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '小山市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tochigi:space-h', 'ボルダリングスペース H（エイチ）', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '小山市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tochigi:prob', 'クライミングジム prob（プロブ）', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '佐野市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tochigi:mibu-climbing', '壬生町総合運動場 ボルダリング施設', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '下都賀郡', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tochigi:zone', 'ボルダリングジム ZONE（ゾーン）', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '那須塩原市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tochigi:berry-wall', 'BERRY WALL（ベリーウォール ） クライミングジム', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '真岡市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:tochigi:t-rox', 'ボルダリングジム T-Rox（ティーロックス）', 'Rockgymの栃木県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '矢板市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/tochigi/', 'Rockgym 栃木県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),

  ('rockgym:gunma:zero-isesaki', 'クライミングジム ZE-RO（ゼロ） 伊勢崎店', 'Rockgymの群馬県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '伊勢崎市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/gunma/', 'Rockgym 群馬県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:gunma:ranbo', 'クライミングジム RANBO（ランボ）', 'Rockgymの群馬県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '伊勢崎市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/gunma/', 'Rockgym 群馬県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:gunma:blue-bird', 'Blue Bird（ブルーバード） ボルダリングジム', 'Rockgymの群馬県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '太田市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/gunma/', 'Rockgym 群馬県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:gunma:landmark', 'Bouldering Spot Landmark（ボルダリングスポットランドマーク）', 'Rockgymの群馬県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '渋川市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/gunma/', 'Rockgym 群馬県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:gunma:white-rock', 'クライミングジム WHITE ROCK（ホワイトロック）', 'Rockgymの群馬県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '高崎市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/gunma/', 'Rockgym 群馬県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:gunma:goofee', 'クライミングジム GooFee（グーフィー）', 'Rockgymの群馬県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '高崎市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/gunma/', 'Rockgym 群馬県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:gunma:and-energy', 'And Energy Bouldering（アンドエネルギーボルダリング）', 'Rockgymの群馬県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '沼田市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/gunma/', 'Rockgym 群馬県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:gunma:wall-street', 'クライミングジム ウォールストリート', 'Rockgymの群馬県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', '前橋市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/gunma/', 'Rockgym 群馬県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published'),
  ('rockgym:gunma:cozy', 'クライミングジム COZY', 'Rockgymの群馬県クライミング施設一覧で存在確認した関東圏ジム。公式ページ確認後に詳細を上書きする。', 'みどり市', 'directory_crosscheck', 'https://rockgym.jp/gym-all/gunma/', 'Rockgym 群馬県のクライミング施設一覧', '2026-05-10 00:00:00+09', 'summary_with_link', 'published')
ON CONFLICT ("source_external_id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = COALESCE("gyms"."description", EXCLUDED."description"),
  "area" = EXCLUDED."area",
  "source_verified_at" = EXCLUDED."source_verified_at",
  "status" = EXCLUDED."status",
  "updated_at" = now(),
  "deleted_at" = NULL;

-- Official-source enrichment batch 1.
-- These rows have been checked against the gym/operator official sites on
-- 2026-05-10 and therefore replace the directory-only source fields.
INSERT INTO "gyms" (
  "source_external_id",
  "name",
  "description",
  "address",
  "area",
  "website_url",
  "instagram_handle",
  "instagram_url",
  "opening_hours_text",
  "source_type",
  "source_url",
  "source_attribution",
  "source_verified_at",
  "source_policy",
  "status"
)
VALUES
  (
    'rockgym:tokyo:prime-climbing',
    'PRIME CLIMBING',
    '茅場町駅/八丁堀駅から徒歩5分のボルダリングジム。公式サイトで住所・営業時間・アクセスを確認済み。',
    '東京都中央区新川2丁目6番8号 YHビル地下1階',
    '中央区',
    'https://primeclimbing.com/',
    NULL,
    'https://www.instagram.com/primeclimbing/',
    '月・金 14:30-22:30 / 火水木 10:00-22:30 / 土 10:00-21:00 / 日祝 10:00-18:00',
    'official_site',
    'https://primeclimbing.com/',
    'PRIME CLIMBING 公式サイト',
    '2026-05-10 00:00:00+09',
    'summary_with_link',
    'published'
  ),
  (
    'rockgym:tokyo:boulcom-tokyo',
    'BOULCOM 東京店',
    '大手町・小川町・淡路町・神田から徒歩圏のボルダリングジム。公式サイトで住所・営業時間・問い合わせ先を確認済み。',
    '東京都千代田区内神田1丁目13-1 豊島屋ビルB2',
    '千代田区',
    'https://boulcom.jp/tokyo/',
    NULL,
    NULL,
    '年中無休 7:00-23:00 / 土日祝 10:00-21:00',
    'official_site',
    'https://boulcom.jp/tokyo/',
    'BOULCOM 東京店 公式サイト',
    '2026-05-10 00:00:00+09',
    'summary_with_link',
    'published'
  ),
  (
    'rockgym:tokyo:spider',
    'クライミングジムSPIDER',
    '麻布十番駅から徒歩5分のクライミングジム。公式サイトで住所・営業時間・最新のお知らせを確認済み。',
    '東京都港区南麻布1-3-16 1階',
    '港区',
    'https://climbing-spider.com/',
    NULL,
    'https://www.instagram.com/climbing_spider/',
    '平日 14:00-22:00 / 土日祝 6:00-19:00 / 不定期',
    'official_site',
    'https://climbing-spider.com/',
    'クライミングジムSPIDER 公式サイト',
    '2026-05-10 00:00:00+09',
    'summary_with_link',
    'published'
  ),
  (
    'rockgym:tokyo:urban-base-camp-shinjuku',
    'Urban Base Camp 新宿',
    '西武新宿駅から徒歩3分、JR新宿駅西口から徒歩5分のBase Camp系列ジム。公式サイトで住所・営業時間・店舗情報を確認済み。',
    '東京都新宿区西新宿7-3-1 三光パークビル B1F',
    '新宿区',
    'https://b-camp.jp/shinjuku/',
    'basecamp_shinjuku',
    'https://www.instagram.com/basecamp_shinjuku/',
    '平日 10:00-23:00 / 土日祝 10:00-22:00 / 定休日なし、臨時休業あり',
    'official_site',
    'https://b-camp.jp/shinjuku/access/',
    'Urban Base Camp 新宿 公式サイト',
    '2026-05-10 00:00:00+09',
    'summary_with_link',
    'published'
  ),
  (
    'rockgym:tokyo:everfree',
    'Everfree Climbing Gym',
    '四ツ谷駅徒歩4分のボルダリングジム。公式サイトで移転後の住所・営業時間・営業中の店舗情報を確認済み。',
    '東京都新宿区四谷2-1 四谷ビル1F',
    '新宿区',
    'https://everfree-climbing.com/',
    NULL,
    NULL,
    '平日 13:00-23:00 / 土日祝 10:00-20:00',
    'official_site',
    'https://everfree-climbing.com/',
    'Everfree Climbing Gym 公式サイト',
    '2026-05-10 00:00:00+09',
    'summary_with_link',
    'published'
  ),
  (
    'rockgym:tokyo:rocky-shinjuku-akebonobashi',
    'ROCKY Climbing & Fitness Gym 新宿曙橋店',
    '曙橋駅から徒歩5分のROCKY系列ジム。公式店舗ページで住所・営業時間・店舗一覧上の営業継続を確認済み。',
    '東京都新宿区市谷台町14-6 信川ハイツB1',
    '新宿区',
    'https://www.rockyclimbing.com/shinjukuakebonobashi/',
    NULL,
    NULL,
    '平日 10:00-23:00 / 土日祝 10:00-21:00',
    'official_site',
    'https://www.rockyclimbing.com/shinjukuakebonobashi/',
    'ROCKY 新宿曙橋店 公式サイト',
    '2026-05-10 00:00:00+09',
    'summary_with_link',
    'published'
  ),
  (
    'rockgym:tokyo:beta',
    'BETA Climbing Gym 新宿店',
    '曙橋駅徒歩圏のクライミングジム。公式サイトで新宿店の住所・営業時間・営業中の店舗情報を確認済み。',
    '東京都新宿区住吉町1-14',
    '新宿区',
    'https://beta-climbing.com/',
    NULL,
    NULL,
    '平日 10:00-23:00 / 土日祝 8:00-23:00 / 不定休',
    'official_site',
    'https://beta-climbing.com/',
    'BETA Climbing 公式サイト',
    '2026-05-10 00:00:00+09',
    'summary_with_link',
    'published'
  ),
  (
    'rockgym:tokyo:noborock-takadanobaba',
    'NOBOROCK 高田馬場店',
    '高田馬場駅徒歩4分のNOBOROCK店舗。公式店舗ページで住所・営業時間・2026年5月の営業変更カレンダーを確認済み。',
    '東京都新宿区高田馬場4丁目9-9',
    '新宿区',
    'https://noborock-climbing.com/program/takadanobaba/',
    'noborock_takadanobaba',
    'https://www.instagram.com/noborock_takadanobaba/',
    '平日 10:00-22:45 / 土日祝 10:00-21:00',
    'official_site',
    'https://noborock-climbing.com/program/takadanobaba/',
    'NOBOROCK 高田馬場店 公式サイト',
    '2026-05-10 00:00:00+09',
    'summary_with_link',
    'published'
  ),
  (
    'rockgym:tokyo:noborock-ikebukuro',
    'NOBOROCK 池袋店',
    '池袋駅西口・要町駅から徒歩3分のNOBOROCK店舗。公式店舗ページで住所・営業時間・2026年5月の営業変更カレンダーを確認済み。',
    '東京都豊島区西池袋5-13-12 MKビルB1',
    '豊島区',
    'https://noborock-climbing.com/program/ikebukuro/',
    'noborock_ikebukuro',
    'https://www.instagram.com/noborock_ikebukuro/',
    '平日 10:00-23:00 / 土日祝 10:00-21:00',
    'official_site',
    'https://noborock-climbing.com/program/ikebukuro/',
    'NOBOROCK 池袋店 公式サイト',
    '2026-05-10 00:00:00+09',
    'summary_with_link',
    'published'
  ),
  (
    'rockgym:tokyo:base-camp-tokyo-edogawabashi',
    'Base Camp Tokyo 江戸川橋',
    '江戸川橋駅徒歩6分、神楽坂駅徒歩11分のBase Camp Tokyo店舗。公式アクセスページで住所・営業時間・定休日を確認済み。',
    '東京都文京区水道2-5-23',
    '文京区',
    'https://b-camp.jp/edogawabashi/',
    NULL,
    NULL,
    '平日 12:00-23:00 / 土日祝 10:00-21:00 / 定休日なし、臨時休業あり',
    'official_site',
    'https://b-camp.jp/edogawabashi/access/',
    'Base Camp Tokyo 江戸川橋 公式サイト',
    '2026-05-10 00:00:00+09',
    'summary_with_link',
    'published'
  )
ON CONFLICT ("source_external_id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "address" = EXCLUDED."address",
  "area" = EXCLUDED."area",
  "website_url" = EXCLUDED."website_url",
  "instagram_handle" = EXCLUDED."instagram_handle",
  "instagram_url" = EXCLUDED."instagram_url",
  "opening_hours_text" = EXCLUDED."opening_hours_text",
  "source_type" = EXCLUDED."source_type",
  "source_url" = EXCLUDED."source_url",
  "source_attribution" = EXCLUDED."source_attribution",
  "source_verified_at" = EXCLUDED."source_verified_at",
  "source_policy" = EXCLUDED."source_policy",
  "status" = EXCLUDED."status",
  "updated_at" = now(),
  "deleted_at" = NULL;
