import type { GymSummary } from "./fixtures.js";

// Generated from infra/seeds/0001_kanto_gym_directory.sql.
// Keep the SQL seed as the source of truth; this file lets local development
// show the same public gym inventory when DATABASE_URL is not configured.
export const kantoGymFixtures: GymSummary[] = [
  {
    "id": "rockgym:tokyo:prime-climbing",
    "name": "PRIME CLIMBING",
    "area": "中央区",
    "address": "東京都中央区新川2丁目6番8号 YHビル地下1階",
    "disciplines": "ボルダー",
    "openingHours": "月・金 14:30-22:30 / 火水木 10:00-22:30 / 土 10:00-21:00 / 日祝 10:00-18:00",
    "websiteUrl": "https://primeclimbing.com/",
    "instagramUrl": "https://www.instagram.com/primeclimbing/",
    "sourceUrl": "https://primeclimbing.com/",
    "sourceAttribution": "PRIME CLIMBING 公式サイト",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:boulcom-tokyo",
    "name": "BOULCOM 東京店",
    "area": "千代田区",
    "address": "東京都千代田区内神田1丁目13-1 豊島屋ビルB2",
    "disciplines": "ボルダー",
    "openingHours": "年中無休 7:00-23:00 / 土日祝 10:00-21:00",
    "websiteUrl": "https://boulcom.jp/tokyo/",
    "sourceUrl": "https://boulcom.jp/tokyo/",
    "sourceAttribution": "BOULCOM 東京店 公式サイト",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:sorayon",
    "name": "ボルダリングジム 空の向こうへ四足歩行（そらよん）",
    "area": "港区",
    "address": "港区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:spider",
    "name": "クライミングジムSPIDER",
    "area": "港区",
    "address": "東京都港区南麻布1-3-16 1階",
    "disciplines": "ボルダー",
    "openingHours": "平日 14:00-22:00 / 土日祝 6:00-19:00 / 不定期",
    "websiteUrl": "https://climbing-spider.com/",
    "instagramUrl": "https://www.instagram.com/climbing_spider/",
    "sourceUrl": "https://climbing-spider.com/",
    "sourceAttribution": "クライミングジムSPIDER 公式サイト",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:urban-base-camp-shinjuku",
    "name": "Urban Base Camp 新宿",
    "area": "新宿区",
    "address": "東京都新宿区西新宿7-3-1 三光パークビル B1F",
    "disciplines": "ボルダー",
    "openingHours": "平日 10:00-23:00 / 土日祝 10:00-22:00 / 定休日なし、臨時休業あり",
    "websiteUrl": "https://b-camp.jp/shinjuku/",
    "instagramHandle": "basecamp_shinjuku",
    "instagramUrl": "https://www.instagram.com/basecamp_shinjuku/",
    "sourceUrl": "https://b-camp.jp/shinjuku/access/",
    "sourceAttribution": "Urban Base Camp 新宿 公式サイト",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:everfree",
    "name": "Everfree Climbing Gym",
    "area": "新宿区",
    "address": "東京都新宿区四谷2-1 四谷ビル1F",
    "disciplines": "ボルダー",
    "openingHours": "平日 13:00-23:00 / 土日祝 10:00-20:00",
    "websiteUrl": "https://everfree-climbing.com/",
    "sourceUrl": "https://everfree-climbing.com/",
    "sourceAttribution": "Everfree Climbing Gym 公式サイト",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:rocky-shinjuku-akebonobashi",
    "name": "ROCKY Climbing & Fitness Gym 新宿曙橋店",
    "area": "新宿区",
    "address": "東京都新宿区市谷台町14-6 信川ハイツB1",
    "disciplines": "ボルダー",
    "openingHours": "平日 10:00-23:00 / 土日祝 10:00-21:00",
    "websiteUrl": "https://www.rockyclimbing.com/shinjukuakebonobashi/",
    "sourceUrl": "https://www.rockyclimbing.com/shinjukuakebonobashi/",
    "sourceAttribution": "ROCKY 新宿曙橋店 公式サイト",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:beta",
    "name": "BETA Climbing Gym 新宿店",
    "area": "新宿区",
    "address": "東京都新宿区住吉町1-14",
    "disciplines": "ボルダー",
    "openingHours": "平日 10:00-23:00 / 土日祝 8:00-23:00 / 不定休",
    "websiteUrl": "https://beta-climbing.com/",
    "sourceUrl": "https://beta-climbing.com/",
    "sourceAttribution": "BETA Climbing 公式サイト",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:parkers-tokyo",
    "name": "PARKERS TOKYO",
    "area": "新宿区",
    "address": "新宿区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:noborock-takadanobaba",
    "name": "NOBOROCK 高田馬場店",
    "area": "新宿区",
    "address": "東京都新宿区高田馬場4丁目9-9",
    "disciplines": "ボルダー",
    "openingHours": "平日 10:00-22:45 / 土日祝 10:00-21:00",
    "websiteUrl": "https://noborock-climbing.com/program/takadanobaba/",
    "instagramHandle": "noborock_takadanobaba",
    "instagramUrl": "https://www.instagram.com/noborock_takadanobaba/",
    "sourceUrl": "https://noborock-climbing.com/program/takadanobaba/",
    "sourceAttribution": "NOBOROCK 高田馬場店 公式サイト",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:noborock-ikebukuro",
    "name": "NOBOROCK 池袋店",
    "area": "豊島区",
    "address": "東京都豊島区西池袋5-13-12 MKビルB1",
    "disciplines": "ボルダー",
    "openingHours": "平日 10:00-23:00 / 土日祝 10:00-21:00",
    "websiteUrl": "https://noborock-climbing.com/program/ikebukuro/",
    "instagramHandle": "noborock_ikebukuro",
    "instagramUrl": "https://www.instagram.com/noborock_ikebukuro/",
    "sourceUrl": "https://noborock-climbing.com/program/ikebukuro/",
    "sourceAttribution": "NOBOROCK 池袋店 公式サイト",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:js-ikebukuro",
    "name": "スポーツクライミングスクール・ジム J&S 池袋",
    "area": "豊島区",
    "address": "豊島区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:konami-ikebukuro",
    "name": "コナミスポーツクラブ 池袋",
    "area": "豊島区",
    "address": "豊島区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:spodori",
    "name": "スポドリ！",
    "area": "文京区",
    "address": "文京区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:base-camp-tokyo-edogawabashi",
    "name": "Base Camp Tokyo 江戸川橋",
    "area": "文京区",
    "address": "東京都文京区水道2-5-23",
    "disciplines": "ボルダー",
    "openingHours": "平日 12:00-23:00 / 土日祝 10:00-21:00 / 定休日なし、臨時休業あり",
    "websiteUrl": "https://b-camp.jp/edogawabashi/",
    "sourceUrl": "https://b-camp.jp/edogawabashi/access/",
    "sourceAttribution": "Base Camp Tokyo 江戸川橋 公式サイト",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:boulders",
    "name": "BOULDERS（ボルダーズ） クライミングジム",
    "area": "足立区",
    "address": "足立区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:galaxcity",
    "name": "ギャラクシティ",
    "area": "足立区",
    "address": "足立区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:rhino-and-bird",
    "name": "Rhino and Bird（ライノアンドバード）",
    "area": "荒川区",
    "address": "荒川区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:hutte",
    "name": "クライミングジム Hutte（ヒュッテ）",
    "area": "荒川区",
    "address": "荒川区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:deer",
    "name": "ボルダリング deer（ディア）",
    "area": "江戸川区",
    "address": "江戸川区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:rocklands",
    "name": "クライミングジム ROCKLANDS（ロックランズ）",
    "area": "江戸川区",
    "address": "江戸川区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:bears-rock",
    "name": "ボルダリングジム BEAR’S ROCK（ベアーズロック）",
    "area": "葛飾区",
    "address": "葛飾区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:katsushika-sports-climbing-center",
    "name": "葛飾区東金町運動場 スポーツクライミングセンター",
    "area": "葛飾区",
    "address": "葛飾区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:fish-and-bird",
    "name": "Fish and Bird（フィッシュアンドバード）",
    "area": "江東区",
    "address": "江東区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:fukagawa-sports-center",
    "name": "深川スポーツセンター",
    "area": "江東区",
    "address": "江東区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:base-camp-tokyo-kinshicho",
    "name": "Base Camp Tokyo（ベースキャンプ東京）錦糸町店",
    "area": "江東区",
    "address": "江東区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:livedoor-urban-sports-park",
    "name": "livedoor URBAN SPORTS PARK（ライブドアアーバンスポーツパーク）",
    "area": "江東区",
    "address": "江東区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:headrock",
    "name": "HEADROCK（ヘッドロック） クライミングジム",
    "area": "墨田区",
    "address": "墨田区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:nico",
    "name": "クライミングジム NICO（ニコ）",
    "area": "墨田区",
    "address": "墨田区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:the-stone-session-tokyo",
    "name": "THE STONE SESSION TOKYO",
    "area": "墨田区",
    "address": "墨田区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:granny-higashiueno",
    "name": "ボルダリングジム グラニー 東上野店",
    "area": "台東区",
    "address": "台東区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:b-pump-ogikubo",
    "name": "B-PUMP OGIKUBO 荻窪",
    "area": "杉並区",
    "address": "杉並区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:bleau",
    "name": "ボルダリングスペース BLEAU（ブロー）",
    "area": "杉並区",
    "address": "杉並区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:lago",
    "name": "フィットネスクライミングスタジオ LAGO（ラーゴ）",
    "area": "杉並区",
    "address": "杉並区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:cell",
    "name": "クライミングジム CELL（セル）",
    "area": "世田谷区",
    "address": "世田谷区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:exciting-sancha",
    "name": "スポーツクライミングジム エキサイティング三茶",
    "area": "世田谷区",
    "address": "世田谷区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:quail",
    "name": "Quail（クエール） クライミングジム",
    "area": "練馬区",
    "address": "練馬区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:pop-in",
    "name": "ボルダリングジム POP IN（ポップイン）",
    "area": "大田区",
    "address": "大田区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:piglet",
    "name": "PIGLET（ピグレット） クライミングジム",
    "area": "品川区",
    "address": "品川区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:north-park",
    "name": "ノースパークビル ボルダリングジム",
    "area": "板橋区",
    "address": "板橋区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:the-factory",
    "name": "the FACTORY（ファクトリー）",
    "area": "板橋区",
    "address": "板橋区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:dracaena",
    "name": "クライミングジム ドラセナ",
    "area": "板橋区",
    "address": "板橋区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:underground",
    "name": "ボルダリングジム UNDERGROUND（アンダーグラウンド）",
    "area": "北区",
    "address": "北区",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:camelopardalis",
    "name": "クライミングスタジオ カメロパルダリス",
    "area": "昭島市",
    "address": "昭島市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:play",
    "name": "クライミングジム＆ヨガスタジオ PLAY",
    "area": "昭島市",
    "address": "昭島市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:runout",
    "name": "クライミングジム ランナウト",
    "area": "国分寺市",
    "address": "国分寺市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:jet-set",
    "name": "JET SET（ジェットセット） climbing gym",
    "area": "立川市",
    "address": "立川市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:d-bouldering-plus-lead-tachikawa",
    "name": "ディーボルダリングプラスリード立川",
    "area": "立川市",
    "address": "立川市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:westrock-chofu",
    "name": "クライミングジム WESTROCK（ウエストロック） 調布店",
    "area": "調布市",
    "address": "調布市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:hangout",
    "name": "クライミングジム hangout（ハングアウト）",
    "area": "調布市",
    "address": "調布市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:giri-giri",
    "name": "クライミングジム GIRI.GIRI（ギリギリ）",
    "area": "西東京市",
    "address": "西東京市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:westrock-fuchu",
    "name": "クライミングジム WESTROCK（ウエストロック） 府中店",
    "area": "府中市",
    "address": "府中市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:jam-session-mitaka",
    "name": "ボルダリングジム ジャムセッション三鷹",
    "area": "三鷹市",
    "address": "三鷹市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:isara",
    "name": "クライミングカフェ isara（イサラ）",
    "area": "三鷹市",
    "address": "三鷹市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:volny",
    "name": "クライミングジム VOLNY（ボルニー）",
    "area": "武蔵野市",
    "address": "武蔵野市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:mitaka-gym",
    "name": "ロッククライミング 三鷹ジム",
    "area": "武蔵野市",
    "address": "武蔵野市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:maboo",
    "name": "クライミングジム MABOO（マーブー）",
    "area": "武蔵村山市",
    "address": "武蔵村山市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:maghreb-est",
    "name": "マグレブエスト",
    "area": "多摩市",
    "address": "多摩市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:d-bouldering-hachioji",
    "name": "ディーボルダリング 八王子",
    "area": "八王子市",
    "address": "八王子市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:madrock",
    "name": "クライミングジム マッドロック",
    "area": "八王子市",
    "address": "八王子市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:rockbeans",
    "name": "クライミングジム ROCKBEANS（ロックビーンズ）",
    "area": "八王子市",
    "address": "八王子市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:d-bouldering-plus-nishi-hachioji",
    "name": "ディーボルダリングプラス 西八王子",
    "area": "八王子市",
    "address": "八王子市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:noborock-machida",
    "name": "NOBOROCK（ノボロック） 町田店",
    "area": "町田市",
    "address": "町田市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:nose-machida",
    "name": "クライミングジム NOSE（ノーズ） 町田店",
    "area": "町田市",
    "address": "町田市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:fits",
    "name": "Fits（フィッツ） クライミングジム",
    "area": "町田市",
    "address": "町田市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:caramba",
    "name": "CLIMBING FRONT CARAMBA（カランバ）",
    "area": "西多摩郡",
    "address": "西多摩郡",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tokyo:miyake-recreation-center",
    "name": "三宅村レクリエーションセンター",
    "area": "三宅村",
    "address": "三宅村",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tokyo/",
    "sourceAttribution": "Rockgym 東京都のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:sea-rock",
    "name": "クライミングジム SEA ROCK（シーロック）",
    "area": "足柄下郡",
    "address": "足柄下郡",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:cipher",
    "name": "クライミングジム Cipher（サイファー）",
    "area": "足柄下郡",
    "address": "足柄下郡",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:lamp-plus-aiko-ishida",
    "name": "ボルダリングジム Lamp+（ランププラス） 愛甲石田店",
    "area": "厚木市",
    "address": "厚木市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:hann2-atsugi",
    "name": "ボルダリングジム 攀（HANN2） 厚木店",
    "area": "厚木市",
    "address": "厚木市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:d-bouldering-hon-atsugi",
    "name": "ディーボルダリング本厚木",
    "area": "厚木市",
    "address": "厚木市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:ledge",
    "name": "クライミングスペース Ledge（レッジ）",
    "area": "海老名市",
    "address": "海老名市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:wisteria",
    "name": "クライミング Wisteria（ウィステリア）",
    "area": "小田原市",
    "address": "小田原市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:pump2-kawasaki",
    "name": "PUMP2 川崎",
    "area": "川崎市",
    "address": "川崎市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:boulcom-kawasaki",
    "name": "BOULCOM（ボルコム） 川崎店",
    "area": "川崎市",
    "address": "川崎市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:dogwood-takatsu",
    "name": "DOGWOOD（ドッグウッド） クライミングジム 高津店",
    "area": "川崎市",
    "address": "川崎市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:pocket",
    "name": "クライミングジム POCKET（ポケット）",
    "area": "川崎市",
    "address": "川崎市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:noborock-mizonokuchi",
    "name": "NOBOROCK（ノボロック） 溝ノ口店",
    "area": "川崎市",
    "address": "川崎市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:boulder-boys-klub",
    "name": "ボルダリングジム Boulder Boys Klub",
    "area": "川崎市",
    "address": "川崎市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:bolbol",
    "name": "BolBol（ボルボル）",
    "area": "相模原市",
    "address": "相模原市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:stone-magic",
    "name": "クライミングパーク STONE MAGIC（ストーンマジック）",
    "area": "相模原市",
    "address": "相模原市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:kachill",
    "name": "KaChill カチル",
    "area": "茅ヶ崎市",
    "address": "茅ヶ崎市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:kanagawa-mountain-sports-center",
    "name": "神奈川県立 山岳スポーツセンター",
    "area": "秦野市",
    "address": "秦野市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:hadano-tanzawa-climbing-park",
    "name": "はだの丹沢クライミングパーク",
    "area": "秦野市",
    "address": "秦野市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:sloth",
    "name": "クライミングジム SLOTH（スロース）",
    "area": "平塚市",
    "address": "平塚市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:rock-and-wall",
    "name": "ボルダリングジム Rock&Wall（ロックアンドウォール）",
    "area": "藤沢市",
    "address": "藤沢市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:j-wall",
    "name": "クライミングジム J-WALL",
    "area": "藤沢市",
    "address": "藤沢市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:hat",
    "name": "ボルダリングスペース HAT（ハット）",
    "area": "大和市",
    "address": "大和市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:forge-bouldering",
    "name": "Forge bouldering",
    "area": "横須賀市",
    "address": "横須賀市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:rockspot",
    "name": "ボルダリングジム ROCKSPOT（ロックスポット）",
    "area": "横浜市",
    "address": "横浜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:rise",
    "name": "クライミングジム RISE（ライズ）",
    "area": "横浜市",
    "address": "横浜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:grimrock",
    "name": "GRIMROCK（グリムロック） クライミングジム",
    "area": "横浜市",
    "address": "横浜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:b-pump-yokohama",
    "name": "B-PUMP YOKOHAMA 横浜",
    "area": "横浜市",
    "address": "横浜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:project",
    "name": "クライミングジム Project（プロジェクト）",
    "area": "横浜市",
    "address": "横浜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:climbing-bum-yokohama",
    "name": "クライミングバム 横浜店",
    "area": "横浜市",
    "address": "横浜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:big-rock-hiyoshi",
    "name": "クライミングジム ビッグロック 日吉店",
    "area": "横浜市",
    "address": "横浜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:aladdin",
    "name": "Aladdin（アラジン） クライミング",
    "area": "横浜市",
    "address": "横浜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:share",
    "name": "ボルダリングジム Share（シェア）",
    "area": "横浜市",
    "address": "横浜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:speedy",
    "name": "ボルダリングジム SPEEDY（スピーディー）",
    "area": "横浜市",
    "address": "横浜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:d-bouldering-tsunashima",
    "name": "ディーボルダリング 綱島",
    "area": "横浜市",
    "address": "横浜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:mammut-yokohama",
    "name": "MAMMUT ボルダリングジム 横浜",
    "area": "横浜市",
    "address": "横浜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:folk",
    "name": "folk（フォーク） ボルダリングジム",
    "area": "横浜市",
    "address": "横浜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:peradora-yokohama",
    "name": "PERADORA（ペルアドラ） クライミングジム 横浜",
    "area": "横浜市",
    "address": "横浜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:kanagawa:hann1-samukawa",
    "name": "ボルダリングジム 攀（HANN1） 寒川店",
    "area": "高座郡",
    "address": "高座郡",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/kanagawa/",
    "sourceAttribution": "Rockgym 神奈川県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:bonobo",
    "name": "BONOBO（ボノボ） ボルダリングスペース",
    "area": "上尾市",
    "address": "上尾市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:limestone",
    "name": "LIMESTONE（ライムストーン） クライミングクラブ",
    "area": "入間郡",
    "address": "入間郡",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:base-camp-iruma",
    "name": "Climb Park Base Camp（ベースキャンプ） 入間店",
    "area": "入間市",
    "address": "入間市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:b3-kasukabe",
    "name": "ボルダリングサイトB3春日部",
    "area": "春日部市",
    "address": "春日部市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:kazo-gymnasium",
    "name": "加須市民体育館",
    "area": "加須市",
    "address": "加須市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:maru",
    "name": "クライミングジム MARU（マル）",
    "area": "川口市",
    "address": "川口市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:pump1-kawaguchi",
    "name": "クライミングジム PUMP1 川口",
    "area": "川口市",
    "address": "川口市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:craze-kawaguchi",
    "name": "craze（クレイズ） ボルダリングジム 川口店",
    "area": "川口市",
    "address": "川口市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:rockcraft-kawagoe",
    "name": "ROCKCRAFT（ロッククラフト）川越",
    "area": "川越市",
    "address": "川越市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:monolithe",
    "name": "Monolithe（モノリス） ボルダリングジム",
    "area": "川越市",
    "address": "川越市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:konami-kawagoe",
    "name": "コナミスポーツクラブ 川越",
    "area": "川越市",
    "address": "川越市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:zero-saitama",
    "name": "クライミングジム ZE-RO（ゼロ） さいたま店",
    "area": "北足立郡",
    "address": "北足立郡",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:walrus",
    "name": "クライミングジム Walrus（ウォルラス）",
    "area": "久喜市",
    "address": "久喜市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:overground",
    "name": "ボルダリングジム OVERGROUND（オーバーグラウンド）",
    "area": "鴻巣市",
    "address": "鴻巣市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:be-born",
    "name": "Be born（ビーボーン） クライミングジム",
    "area": "越谷市",
    "address": "越谷市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:rock-cube",
    "name": "ROCK CUBE（ロックキューブ） クライミングジム",
    "area": "越谷市",
    "address": "越谷市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:penguin",
    "name": "クライミングジム Penguin（ペンギン）",
    "area": "さいたま市",
    "address": "さいたま市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:energy-urawa",
    "name": "エナジークライミングジム 浦和店",
    "area": "さいたま市",
    "address": "さいたま市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:noborock-omiya",
    "name": "NOBOROCK（ノボロック） 大宮",
    "area": "さいたま市",
    "address": "さいたま市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:kalma",
    "name": "KALMA（カルマ） クライミングジム",
    "area": "坂戸市",
    "address": "坂戸市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:trip",
    "name": "クライミングジム TRIP",
    "area": "坂戸市",
    "address": "坂戸市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:rout-f",
    "name": "Rout f（ルートエフ） ボルダリングジム",
    "area": "新座市",
    "address": "新座市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:next-gen-bouldering",
    "name": "Next Gen Bouldering（ネクストジェンボルダリング）",
    "area": "新座市",
    "address": "新座市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:ogano-climbing-park",
    "name": "小鹿野町クライミングパーク 神怡舘",
    "area": "秩父郡",
    "address": "秩父郡",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:base-camp-hanno",
    "name": "Boulder Park Base Camp（ベースキャンプ） 飯能店",
    "area": "飯能市",
    "address": "飯能市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:trick-star",
    "name": "TRICK STAR（トリックスター） クライミングジム",
    "area": "飯能市",
    "address": "飯能市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:fukaya-climbing-village",
    "name": "深谷クライミングヴィレッジ",
    "area": "深谷市",
    "address": "深谷市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:lutra-lutra",
    "name": "Lutra Lutra（ルトラルトラ）",
    "area": "深谷市",
    "address": "深谷市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:three-peaks",
    "name": "クライミングジム THREE PEAKS（スリーピークス）",
    "area": "本庄市",
    "address": "本庄市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:okku-rock",
    "name": "クライミングハウス OKKU ROCK（オックロック）",
    "area": "南埼玉郡",
    "address": "南埼玉郡",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:saitama:community-park-yashio",
    "name": "Community Park Yashio",
    "area": "八潮市",
    "address": "八潮市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/saitama/",
    "sourceAttribution": "Rockgym 埼玉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:rocky-inzai",
    "name": "ROCKY（ロッキー） 印西店",
    "area": "印西市",
    "address": "印西市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:matsuyamashita-gymnasium",
    "name": "松山下公園総合体育館",
    "area": "印西市",
    "address": "印西市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:energy-kashiwa",
    "name": "エナジークライミングジム 柏店",
    "area": "柏市",
    "address": "柏市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:altior",
    "name": "ALTIOR（アルティオール）クライミングジム",
    "area": "柏市",
    "address": "柏市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:funny",
    "name": "ボルダリングガレージ FUNNY（ファニー）",
    "area": "鎌ヶ谷市",
    "address": "鎌ヶ谷市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:d-bouldering-plus-soga",
    "name": "ディーボルダリングプラス蘇我",
    "area": "千葉市",
    "address": "千葉市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:tohan-dojo",
    "name": "ボルダリングジム 登攀道場",
    "area": "千葉市",
    "address": "千葉市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:asuka",
    "name": "クライミング飛鳥",
    "area": "千葉市",
    "address": "千葉市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:beaks",
    "name": "BEAKS（ビークス） クライミングスタジオ",
    "area": "千葉市",
    "address": "千葉市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:d-bouldering-plus-lead-kaihimmakuhari",
    "name": "ディーボルダリングプラスリード海浜幕張",
    "area": "千葉市",
    "address": "千葉市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:olioli",
    "name": "クライミングジム OliOli（オリオリ）",
    "area": "長生郡",
    "address": "長生郡",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:granny-minami-nagareyama",
    "name": "ボルダリングジム GRANNY（グラニー） 南流山店",
    "area": "流山市",
    "address": "流山市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:sarukichi",
    "name": "クライミングジム猿吉",
    "area": "東金市",
    "address": "東金市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:d-bouldering-plus-tsudanuma",
    "name": "ディーボルダリングプラス津田沼",
    "area": "習志野市",
    "address": "習志野市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:rocky-funabashi",
    "name": "ROCKY（ロッキー） 船橋店",
    "area": "船橋市",
    "address": "船橋市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:carche-roche",
    "name": "クライミングパーク カルチェロッシュ",
    "area": "松戸市",
    "address": "松戸市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:chiba:d-bouldering-plus-yachiyo",
    "name": "ディーボルダリングプラス八千代",
    "area": "八千代市",
    "address": "八千代市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/chiba/",
    "sourceAttribution": "Rockgym 千葉県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:ibaraki:rocky-tsukuba-ami",
    "name": "ROCKY（ロッキー） つくば阿見店",
    "area": "稲敷郡",
    "address": "稲敷郡",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/ibaraki/",
    "sourceAttribution": "Rockgym 茨城県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:ibaraki:vortex",
    "name": "ボルダリングジム Vortex（ボルテックス）",
    "area": "笠間市",
    "address": "笠間市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/ibaraki/",
    "sourceAttribution": "Rockgym 茨城県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:ibaraki:aoroc",
    "name": "ao_roc.（アオロク） climbing",
    "area": "鹿嶋市",
    "address": "鹿嶋市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/ibaraki/",
    "sourceAttribution": "Rockgym 茨城県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:ibaraki:style-crew",
    "name": "ボルダリングジム Style crew",
    "area": "猿島郡",
    "address": "猿島郡",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/ibaraki/",
    "sourceAttribution": "Rockgym 茨城県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:ibaraki:spole",
    "name": "Spole（スポーレ） クライミングジム",
    "area": "つくば市",
    "address": "つくば市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/ibaraki/",
    "sourceAttribution": "Rockgym 茨城県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:ibaraki:monkey-magic-tsukuba",
    "name": "ボルダリングジム モンキーマジック つくばQ’t",
    "area": "つくば市",
    "address": "つくば市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/ibaraki/",
    "sourceAttribution": "Rockgym 茨城県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:ibaraki:echoes",
    "name": "ECHOES CLIMBING（エコーズ クライミング）",
    "area": "つくばみらい市",
    "address": "つくばみらい市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/ibaraki/",
    "sourceAttribution": "Rockgym 茨城県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:ibaraki:freiheit",
    "name": "ボルダリングジム フライハイト",
    "area": "土浦市",
    "address": "土浦市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/ibaraki/",
    "sourceAttribution": "Rockgym 茨城県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:ibaraki:zero-mito",
    "name": "クライミングジム ZE-RO（ゼロ） 水戸店",
    "area": "水戸市",
    "address": "水戸市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/ibaraki/",
    "sourceAttribution": "Rockgym 茨城県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:ibaraki:avue",
    "name": "水戸シティロックジム avue（アヴュー）",
    "area": "水戸市",
    "address": "水戸市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/ibaraki/",
    "sourceAttribution": "Rockgym 茨城県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:mountain-cliff",
    "name": "MOUNTAIN CLIFF（マウンテンクリフ）",
    "area": "足利市",
    "address": "足利市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:lost-canyon",
    "name": "クライミングジム LOST CANYON（ロストキャニオン）",
    "area": "宇都宮市",
    "address": "宇都宮市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:suncul",
    "name": "SUNCUL（サンカル）",
    "area": "宇都宮市",
    "address": "宇都宮市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:flash",
    "name": "クライミングジム FLASH（フラッシュ）",
    "area": "宇都宮市",
    "address": "宇都宮市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:zero-utsunomiya-shimoguri",
    "name": "クライミングジム ZE-RO（ゼロ） 宇都宮下栗店",
    "area": "宇都宮市",
    "address": "宇都宮市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:zero-utsunomiya",
    "name": "クライミングジム ZE-RO（ゼロ） 宇都宮店",
    "area": "宇都宮市",
    "address": "宇都宮市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:rockyn",
    "name": "クライミングジム RocKY’N（ロッキン）",
    "area": "宇都宮市",
    "address": "宇都宮市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:ark",
    "name": "クライミングジム アーク",
    "area": "大田原市",
    "address": "大田原市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:prost",
    "name": "Prost（プロスト） クライミングクラブ",
    "area": "小山市",
    "address": "小山市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:space-h",
    "name": "ボルダリングスペース H（エイチ）",
    "area": "小山市",
    "address": "小山市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:prob",
    "name": "クライミングジム prob（プロブ）",
    "area": "佐野市",
    "address": "佐野市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:mibu-climbing",
    "name": "壬生町総合運動場 ボルダリング施設",
    "area": "下都賀郡",
    "address": "下都賀郡",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:zone",
    "name": "ボルダリングジム ZONE（ゾーン）",
    "area": "那須塩原市",
    "address": "那須塩原市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:berry-wall",
    "name": "BERRY WALL（ベリーウォール ） クライミングジム",
    "area": "真岡市",
    "address": "真岡市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:tochigi:t-rox",
    "name": "ボルダリングジム T-Rox（ティーロックス）",
    "area": "矢板市",
    "address": "矢板市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/tochigi/",
    "sourceAttribution": "Rockgym 栃木県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:gunma:zero-isesaki",
    "name": "クライミングジム ZE-RO（ゼロ） 伊勢崎店",
    "area": "伊勢崎市",
    "address": "伊勢崎市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/gunma/",
    "sourceAttribution": "Rockgym 群馬県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:gunma:ranbo",
    "name": "クライミングジム RANBO（ランボ）",
    "area": "伊勢崎市",
    "address": "伊勢崎市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/gunma/",
    "sourceAttribution": "Rockgym 群馬県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:gunma:blue-bird",
    "name": "Blue Bird（ブルーバード） ボルダリングジム",
    "area": "太田市",
    "address": "太田市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/gunma/",
    "sourceAttribution": "Rockgym 群馬県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:gunma:landmark",
    "name": "Bouldering Spot Landmark（ボルダリングスポットランドマーク）",
    "area": "渋川市",
    "address": "渋川市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/gunma/",
    "sourceAttribution": "Rockgym 群馬県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:gunma:white-rock",
    "name": "クライミングジム WHITE ROCK（ホワイトロック）",
    "area": "高崎市",
    "address": "高崎市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/gunma/",
    "sourceAttribution": "Rockgym 群馬県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:gunma:goofee",
    "name": "クライミングジム GooFee（グーフィー）",
    "area": "高崎市",
    "address": "高崎市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/gunma/",
    "sourceAttribution": "Rockgym 群馬県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:gunma:and-energy",
    "name": "And Energy Bouldering（アンドエネルギーボルダリング）",
    "area": "沼田市",
    "address": "沼田市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/gunma/",
    "sourceAttribution": "Rockgym 群馬県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:gunma:wall-street",
    "name": "クライミングジム ウォールストリート",
    "area": "前橋市",
    "address": "前橋市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/gunma/",
    "sourceAttribution": "Rockgym 群馬県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  },
  {
    "id": "rockgym:gunma:cozy",
    "name": "クライミングジム COZY",
    "area": "みどり市",
    "address": "みどり市",
    "disciplines": "クライミング",
    "openingHours": "",
    "sourceUrl": "https://rockgym.jp/gym-all/gunma/",
    "sourceAttribution": "Rockgym 群馬県のクライミング施設一覧",
    "sourceVerifiedAt": "2026-05-10",
    "saved": false
  }
];
