-- Generated by scripts/promote-source-observations.mjs
-- generated_at: 2026-05-12T02:55:12.560Z
-- mode: draft_review
-- This patch only stores review candidates unless ZAC_PROMOTE_OBSERVATIONS_APPROVE=1 was set.
INSERT INTO "events" (
  "id",
  "gym_id",
  "category",
  "title",
  "summary",
  "description",
  "starts_at",
  "ends_at",
  "capacity_text",
  "source_type",
  "source_url",
  "source_account",
  "source_published_at",
  "source_fetched_at",
  "source_quote",
  "source_raw_text",
  "source_policy",
  "extraction_confidence",
  "review_status",
  "reviewed_at",
  "status",
  "visibility",
  "created_by"
)
SELECT *
FROM (VALUES
  ('88ab98bd-0415-41ba-82b5-75bb07ccc022'::uuid, '6d6885be-a886-4941-a7e2-31c18f7adff4'::uuid, 'competition', '開催発表', 'B-PUMP OGIKUBOの公式Instagram投稿をコンペ・大会として確認。 日付候補は2026/06/06。公開UIに出す前に詳細確認が必要。', 'B-PUMP OGIKUBOの公式Instagram投稿をコンペ・大会として確認。 日付候補は2026/06/06。公開UIに出す前に詳細確認が必要。 詳細や続報は公式Instagramで確認してください。', '2026-06-06T01:00:00.000Z'::timestamptz, '2026-06-06T02:00:00.000Z'::timestamptz, '公式Instagramで確認', 'official_instagram', 'https://www.instagram.com/p/DXHComvEz5I/', 'B-PUMP OGIKUBO', '2026-04-14T11:15:09.000Z'::timestamptz, '2026-05-12T02:36:44.321Z'::timestamptz, '【開催発表】', NULL, 'summary_with_link', 0.72::numeric, 'pending', NULL::timestamptz, 'draft', 'public', '00000000-0000-4000-8000-000000000001'::uuid)
) AS v(
  "id",
  "gym_id",
  "category",
  "title",
  "summary",
  "description",
  "starts_at",
  "ends_at",
  "capacity_text",
  "source_type",
  "source_url",
  "source_account",
  "source_published_at",
  "source_fetched_at",
  "source_quote",
  "source_raw_text",
  "source_policy",
  "extraction_confidence",
  "review_status",
  "reviewed_at",
  "status",
  "visibility",
  "created_by"
)
WHERE NOT EXISTS (
  SELECT 1 FROM "events" e WHERE e."deleted_at" IS NULL AND e."source_url" = v."source_url"
);

WITH promoted_observations("id", "event_id") AS (
  VALUES
  ('18f4326d-8801-4dc8-9902-85bcccd2d2d2'::uuid, '88ab98bd-0415-41ba-82b5-75bb07ccc022'::uuid)
)
UPDATE "source_post_observations" o
SET
  "review_status" = 'event_candidate',
  "decision_note" = trim(concat_ws(' ', o."decision_note", 'Promoted to draft event candidate', promoted_observations."event_id"::text)),
  "updated_at" = now()
FROM promoted_observations
WHERE o."id" = promoted_observations."id";
