-- Generated by scripts/promote-source-observations.mjs
-- generated_at: 2026-05-26T10:02:59.001Z
-- mode: draft_review
-- This patch only stores review candidates unless ZAC_PROMOTE_OBSERVATIONS_APPROVE=1 was set.
INSERT INTO "events" (
  "id",
  "gym_id",
  "category",
  "title",
  "summary",
  "description",
  "starts_at",
  "ends_at",
  "capacity_text",
  "source_type",
  "source_url",
  "source_account",
  "source_published_at",
  "source_fetched_at",
  "source_quote",
  "source_raw_text",
  "source_policy",
  "extraction_confidence",
  "review_status",
  "reviewed_at",
  "status",
  "visibility",
  "created_by"
)
SELECT *
FROM (VALUES
  ('a337cd67-6d47-4937-b515-84dcd6351d1e'::uuid, 'a3ef4def-5c09-4e49-ac12-c556018e8c2c'::uuid, 'route_set', 'ALTIOR（アルティオール）クライミングジム grade:2D/V9/7c', 'ALTIOR（アルティオール）クライミングジムの公式情報に基づく2026/09/07のセット・ホールド替え情報です。対象エリアや利用制限は公式情報で確認してください。', 'ALTIOR（アルティオール）クライミングジムの公式情報に基づく2026/09/07のセット・ホールド替え情報です。対象エリアや利用制限は公式情報で確認してください。 最新状況はリンク先の公式情報を確認してください。', '2026-09-07T08:00:00.000Z'::timestamptz, '2026-09-07T09:00:00.000Z'::timestamptz, '対象エリア・利用制限は公式情報で確認', 'official_instagram', 'https://www.instagram.com/reel/DYyTbeCvx_P/', 'ALTIOR（アルティオール）クライミングジム', NULL::timestamptz, '2026-05-26T09:57:42.926Z'::timestamptz, 'grade:2D/V9/7c', NULL, 'summary_with_link', 0.72::numeric, 'pending', NULL::timestamptz, 'draft', 'public', '00000000-0000-4000-8000-000000000001'::uuid)
) AS v(
  "id",
  "gym_id",
  "category",
  "title",
  "summary",
  "description",
  "starts_at",
  "ends_at",
  "capacity_text",
  "source_type",
  "source_url",
  "source_account",
  "source_published_at",
  "source_fetched_at",
  "source_quote",
  "source_raw_text",
  "source_policy",
  "extraction_confidence",
  "review_status",
  "reviewed_at",
  "status",
  "visibility",
  "created_by"
)
WHERE NOT EXISTS (
  SELECT 1 FROM "events" e WHERE e."deleted_at" IS NULL AND e."source_url" = v."source_url"
);

WITH promoted_observations("id", "event_id") AS (
  VALUES
  ('7e93691b-a475-476d-8a74-fa0d6badbe5f'::uuid, 'a337cd67-6d47-4937-b515-84dcd6351d1e'::uuid)
)
UPDATE "source_post_observations" o
SET
  "review_status" = 'event_candidate',
  "decision_note" = trim(concat_ws(' ', o."decision_note", 'Promoted to draft event candidate', promoted_observations."event_id"::text)),
  "updated_at" = now()
FROM promoted_observations
WHERE o."id" = promoted_observations."id";

WITH ignored_observations("id") AS (
  VALUES
  ('6f922b47-2325-4455-9b78-2d8833d17f35'::uuid),
  ('4ff8a90d-0a83-4d8e-a512-136713edbadc'::uuid),
  ('2b8f469f-6d74-43eb-9fdd-248c4297ef5f'::uuid),
  ('dbca0c60-5eea-4b54-ae8b-6adc3d6dad49'::uuid),
  ('29a2a852-9962-43a8-88d8-4250b8942d6a'::uuid),
  ('c432a667-0d15-4c60-a949-51c451958b34'::uuid),
  ('cb5594bf-0c72-40a6-a8c6-d67857cce86a'::uuid),
  ('4087b937-a7b7-4c73-a420-a5e6c718da6a'::uuid),
  ('cf253e8f-9994-4421-a29b-d77bce360f1f'::uuid),
  ('d61f25a4-60ed-4565-b91c-b79966d87f1f'::uuid),
  ('64e309b4-3290-44be-bf32-e92da6d3d47e'::uuid),
  ('833036af-496c-4ff4-9684-0659ece5436d'::uuid),
  ('f329d311-25ed-4299-84b8-5869300bc720'::uuid),
  ('88eb5281-5598-4d90-a25d-46c7e29c0ff4'::uuid),
  ('d6bdb609-45bb-4349-99fb-ed962b9fc719'::uuid),
  ('99e4fd3b-9924-4e64-bc16-2c452af1cf8e'::uuid),
  ('5b617934-0d84-4032-a6ab-62e50bde5542'::uuid),
  ('2ab6efd1-5612-4eb4-be58-0d4d0f771caf'::uuid),
  ('a26d6b19-f63a-4f33-85f0-3c7dbe195709'::uuid),
  ('caad4002-c688-4fe3-82e7-4d51cacfb144'::uuid),
  ('077b5763-4ce1-4043-ab1d-e0d8d2d22b97'::uuid),
  ('57fab4fc-ea85-43b4-a94f-f623e399e007'::uuid),
  ('53404b06-0bcb-49e0-a5e9-add2ffeba613'::uuid),
  ('616040c2-1ad7-4768-aa58-4a2645b66cdb'::uuid),
  ('a03e7591-e98c-4f9a-8daf-213febeb61ce'::uuid),
  ('c2493e65-1fd4-421b-8b69-c65a147d1617'::uuid),
  ('19c7ffce-05b9-4114-a99c-dae7e872c80b'::uuid)
)
UPDATE "source_post_observations" o
SET
  "review_status" = 'ignored',
  "decision_note" = trim(concat_ws(' ', o."decision_note", 'Skipped by promotion quality gate')),
  "updated_at" = now()
FROM ignored_observations
WHERE o."id" = ignored_observations."id"
  AND o."review_status" = 'pending';


