-- Generated by scripts/promote-source-observations.mjs
-- generated_at: 2026-05-20T15:43:24.543Z
-- mode: draft_review
-- This patch only stores review candidates unless ZAC_PROMOTE_OBSERVATIONS_APPROVE=1 was set.
-- No eligible source_post_observations to promote.

WITH stale_event_candidates("id") AS (
  VALUES
  ('062bffd7-45e6-4cc4-b4fb-e280ad7bee44'::uuid),
  ('729d66eb-f805-48bf-9d91-d8b31f2d4818'::uuid)
)
UPDATE "events" e
SET
  "review_status" = 'rejected',
  "reviewed_at" = now(),
  "updated_at" = now()
FROM stale_event_candidates
WHERE e."id" = stale_event_candidates."id"
  AND e."review_status" = 'pending'
  AND e."status" = 'draft';
